version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--ping"
      - "--providers.docker=true"
      #- "--providers.docker.endpoint=unix:///var/run/docker.sock"
      #- "--providers.docker.network=traefik-public"
      #- "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"        
    ports:
      # The HTTP port
      - "80:80"
       # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  # ...
  spperformer:
    # A container that exposes an API to show its IP address
    image: skalena/spperformer
    labels:
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      #- "traefik.docker.network=traefik-public"
    expose:
      - "7780"  
      #docker-compose up -d --scale spperformer=2
  spperformer2:
    # A container that exposes an API to show its IP address
     image: skalena/spperformer
     labels:
       - "traefik.http.routers.spperformer2.rule=Host(`localhost`)"
       #- "traefik.docker.network=traefik-public"
     expose:
      - "7780"  

#docker-compose up -d --scale spperformer=2      